package net.sclan.minigames.ui

sealed class Screen {
    object Home : Screen()
    data class GameSetup(val game: GameId) : Screen()
    data class TicTacToe(val difficulty: TicTacToeDifficulty) : Screen()
    data class Game2048(val difficulty: TileMergeDifficulty) : Screen()
    data class Minesweeper(val difficulty: MinesweeperDifficulty) : Screen()
    data class MemoryMatch(val difficulty: MemoryMatchDifficulty) : Screen()
    data class ReactionTap(val mode: ReactionTapMode) : Screen()
    data class Snake(val difficulty: SnakeDifficulty) : Screen()
    data class FourInARow(val mode: FourInARowMode) : Screen()
    data class DotsAndBoxes(val size: DotsAndBoxesSize) : Screen()
    data class WordSearch(val difficulty: WordSearchDifficulty) : Screen()
    data class CodeBreaker(val difficulty: CodeBreakerDifficulty) : Screen()
    data class Sudoku(val difficulty: SudokuDifficulty) : Screen()
    data class BubbleWrap(val size: BubbleWrapSize) : Screen()
    data class TimingStack(val speed: TimingStackSpeed) : Screen()
    data class MazeRunner(val size: MazeSize) : Screen()
    data class AnagramTiles(val length: AnagramLength) : Screen()
    data class Mancala(val mode: MancalaMode) : Screen()
    data class SimonSays(val speed: SimonSpeed) : Screen()
    data class WaterSort(val difficulty: WaterSortDifficulty) : Screen()
    data class NutsAndBolts(val difficulty: WaterSortDifficulty) : Screen()
    data class ColorFill(val difficulty: ColorFillDifficulty) : Screen()
    data class ColorBlocks(val difficulty: ColorBlocksDifficulty) : Screen()
    data class Escape(val pack: EscapePack) : Screen()
    data class MazePaint(val size: MazeSize) : Screen()
    data class FlappyJump(val difficulty: FlappyDifficulty) : Screen()
    data class SandFall(val brush: SandBrush) : Screen()
    object BlockFill : Screen()
    object MergeChain : Screen()
    data class CrossMath(val difficulty: CrossMathDifficulty) : Screen()
    data class NumberConnect(val difficulty: NumberConnectDifficulty) : Screen()
    object Solitaire : Screen()
    object War : Screen()
    object Blackjack : Screen()
    object Dominoes : Screen()
    object Checkers : Screen()
    data class Ludo(val mode: LudoMode) : Screen()
    object WordRescue : Screen()
    object WordGuess : Screen()
    data class SlidingPuzzle(val size: SlidingSize) : Screen()
    data class Pong(val mode: PongMode) : Screen()
    object PenaltyKicks : Screen()
    object FidgetSpinner : Screen()
    object ChalkDoodle : Screen()
    object WordLadder : Screen()
    data class AirHockey(val mode: PongMode) : Screen()
    object Pool : Screen()
    object Settings : Screen()
}
